name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # npm install --only=prod
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        #REMOTE_PATH
        #/home/usernameserver/codebase.... 
        script: |
          #pwd
          #whoami
          cd ${{ secrets.REMOTE_PATH }}
          git fetch -v
          git status
          git pull origin master
          git status
          sudo php artisan cache:clear
          sudo php artisan view:clear
          sudo php artisan route:clear
          sudo php artisan config:cache
          sudo php artisan config:clear
